### ISSUE TITLE
Pasta de instalação

### ISSUE THREAD

**Issue by DragonOfWar** [ColmeiaUDESC/Guia-Aseprite#11]
Seria interessante se pudesse indicar a pasta de instalação do Aseprite.

**Comment by MrBertemes** [comment]
Indicar no guia ?

**Comment by DragonOfWar** [comment]
> Indicar no guia ?

Eu estaria me referindo na hora de executar o script. Daria pra passar como uma opção no script aonde deseja instalar a pasta aseprite.
No caso do guia, acho q deveríamos deixar como está para não confundir quem está seguindo ele.
